<?php include "header.phtml" ?>
    <!---------- Body starts --------------->

    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href=<?= $linkTo('customerIndex'); ?>>First National Bank</a>
            </div>
            <ul class="nav navbar-nav">
                <li><a href=<?= $linkTo('customerIndex'); ?>>Home</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li><a href=<?= $linkTo('customerRegister'); ?>><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
            </ul>
        </div>
    </nav>

    <div class="container">
        <form action="dashboard" method="post">
            <div class="form-group">
                <label>Email:</label>
                <input type="email" class="form-control notInline" placeholder="Enter email" name="email" required="required">
            </div>
            <div class="form-group">
                <label>Password:</label>
                <input type="password" class="form-control notInline" placeholder="Enter password" name="password" required="required">
            </div>
            <button name="dashboard" type="submit" class="btn btn-default">Log in</button>
        </form>
    </div>
    <!---------- Body ends -------------------->
<?php include "footer.phtml" ?>